const sections = [...document.querySelectorAll(".section[id]")];
const sidebarLinks = [...document.querySelectorAll(".sidebar a")];
const languageButtons = [...document.querySelectorAll("[data-lang-switch]")];
let currentLanguage = "zh";

const translations = {
  zh: {
    "nav.tracks": "赛道",
    "nav.corpus": "语料库",
    "nav.workshop": "工作坊",
    "nav.overview": "概览",
    "nav.materials": "素材",
    "nav.getStarted": "开始使用",
    "sidebar.title": "文档目录",
    "sidebar.intro": "项目介绍",
    "sidebar.tracksTime": "赛道与节奏",
    "sidebar.corpus": "语料库",
    "sidebar.cases": "案例库",
    "sidebar.workshop": "共创流程",
    "sidebar.skills": "Skill 系统",
    "sidebar.outputs": "产出要求",
    "tools.codex": "Codex 配置",
    "tools.skills": "Skill 安装",
    "tools.verify": "环境验证",
    "hero.eyebrow": "太空艺术设计实验室",
    "hero.title": "国际太空艺术设计共创营",
    "hero.subtitle": "International Space Art & Design Collaborative Camp",
    "hero.lede":
      "从国际共创、知识赋能到原型制作、评审展览与持续孵化。项目把航天知识转化为可理解、可感知、可体验的未来生活提案。",
    "hero.ctaTracks": "查看六大赛道",
    "hero.ctaWorkshop": "查看工作坊流程",
    "hero.ctaSkills": "查看 Skill 系统",
    "metric.tracks": "赛道",
    "metric.tutors": "导师",
    "metric.regions": "国家和地区",
    "metric.institutions": "院校",
    "mission.eyebrow": "项目主旨",
    "mission.title": "以艺术设计回应未来太空生活",
    "mission.callout":
      "共创营汇聚国际顶尖艺术设计院校师生与全球航天领域专家，通过跨学科协作，将航天任务、太空环境、未来社会与公众体验连接成一个可创作、可展示、可孵化的未来文明实验场。",
    "mission.knowledge": "航天、艺术与设计跨界授课，建立共同知识底座。",
    "mission.cocreation": "跨文化团队围绕六个方向推进概念、原型与展陈方案。",
    "mission.exhibition": "优秀作品进入联合展览，形成太空未来生活的全景叙事。",
    "mission.validation": "后续项目可继续孵化，并面向太空实验或公众传播验证。",
    "tracks.eyebrow": "六大赛道",
    "tracks.title": "六条路径共同回答未来太空生活",
    "track1.title": "航天愿景与未来叙事",
    "track1.desc": "文化载荷、任务叙事、科普传播与公众参与",
    "track1.output": "交付：数字叙事作品、公众互动、展陈载体",
    "track2.title": "空间栖居与数字建造",
    "track2.desc": "火星极地栖居、数字建造、材料与生命支持",
    "track2.output": "交付：系统原型、空间载体、交互系统",
    "track3.title": "创意载荷与公共艺术",
    "track3.desc": "太空环境与载荷约束下的公共艺术边界",
    "track3.output": "交付：核心作品、展陈载体、来源/伦理记录",
    "track4.title": "地外日常与体验设计",
    "track4.desc": "饮食、清洁、节律、社交与游憩的地外生活原型",
    "track4.output": "交付：体验原型、设计档案、概念视频、展板",
    "track5.title": "太空计算与具身智能",
    "track5.desc": "智能体在舱内服务、星表探索与身体增强中的表达",
    "track5.output": "交付：实体原型、视觉方案、视频、展板",
    "track6.title": "太空时尚与人机进化",
    "track6.desc": "服装作为身体与异星世界之间的第二层肌肤",
    "track6.output": "交付：实体服装/可穿戴部件、视觉档案、视频、展板",
    "timeline.eyebrow": "项目节奏",
    "timeline.title": "三阶段完成知识赋能、方案孵化与展览展示",
    "timeline.phase1": "阶段 01",
    "timeline.phase1Title": "专家讲座与知识赋能",
    "timeline.phase1Desc": "跨学科讲座建立航天、艺术、设计与技术的共同语言。",
    "timeline.phase2": "阶段 02",
    "timeline.phase2Title": "创意探索与方案孵化",
    "timeline.phase2Desc": "团队深化概念、完成试验并形成可展示原型。",
    "timeline.phase3": "阶段 03",
    "timeline.phase3Title": "评审遴选与展览展示",
    "timeline.phase3Desc": "通过路演、评审、遴选与联合展览推进持续孵化。",
    "corpus.eyebrow": "语料库",
    "corpus.title": "四组语料为概念生成提供未来信号",
    "corpus.viewDetails": "查看资料页",
    "corpus1.title": "语料包 1：独立于地球",
    "corpus1.short": "独立于地球",
    "corpus1.desc": "火星长期定居所需的关键技术信号，从空气、水、电力到生态自治。",
    "corpus1.signals": "IE-01 到 IE-30",
    "corpus1.use": "生命支持、栖居系统、资源闭环",
    "corpus2.title": "语料包 2：地外迷域",
    "corpus2.short": "地外迷域",
    "corpus2.desc": "宇航员心理、生理及感官异化体验，用于设计情绪支持与感知干预。",
    "corpus2.signals": "AM-01 到 AM-30",
    "corpus2.use": "地外日常、体验设计、太空心理",
    "corpus3.title": "语料包 3：隐藏同款",
    "corpus3.short": "隐藏同款",
    "corpus3.desc": "航天技术向地球日常产品转化的案例库，连接极端环境与民用创新。",
    "corpus3.signals": "HT-01 到 HT-30",
    "corpus3.use": "产品转译、材料创新、生活用品",
    "corpus4.title": "语料包 4：新太空仪式感物件",
    "corpus4.short": "新太空仪式感物件",
    "corpus4.desc": "真实太空物件中的象征、纪念与仪式意义，支撑叙事与公共艺术。",
    "corpus4.signals": "RS-01 到 RS-33",
    "corpus4.use": "文化载荷、纪念物、太空仪式",
    "cases.eyebrow": "案例库",
    "cases.title": "四组议题案例为设计推演提供参考原型",
    "case1.title": "案例库 1：具身体验与交互设计",
    "case1.short": "具身体验与交互设计",
    "case1.desc": "当身体的熟悉性失效，如何通过结构化的符号行为重建人与世界的连接。",
    "case1.signals": "EI-01 到 EI-20",
    "case1.use": "身体—环境—材料关系、感知设计",
    "case2.title": "案例库 2：文化结构与仪式演化",
    "case2.short": "文化结构与仪式演化",
    "case2.desc": "如何将地球文明的仪式结构与情感代码延伸到太空文明中。",
    "case2.signals": "CR-01 到 CR-20",
    "case2.use": "仪式结构、文化系统、群体情感",
    "case3.title": "案例库 3：时间重构与情感连接",
    "case3.short": "时间重构与情感连接",
    "case3.desc": "当昼夜节律与季节变化失效，如何通过设计重建情感、记忆与仪式。",
    "case3.signals": "TE-01 到 TE-17",
    "case3.use": "时间感知、情感与记忆设计",
    "case4.title": "案例库 4：非地理性共享空间",
    "case4.short": "非地理性共享空间",
    "case4.desc": "当空间失去地理意义，如何建立公共感与共识。",
    "case4.signals": "NS-01 到 NS-20",
    "case4.use": "公共感、共识系统、共享记忆",
    "workshop.eyebrow": "AI 共创工作坊",
    "workshop.title": "Future Design Thinking 工作流",
    "workshop.step1": "浏览并选择未来信号。",
    "workshop.step2": "选择或输入地方挑战，AI 可辅助扩展。",
    "workshop.step3": "生成 Provotyping Card 与 Interpretation 句式。",
    "workshop.step4": "生成未来新闻标题和情境图像。",
    "workshop.step5": "从 2050 目标倒推 2040 与 2030 行动。",
    "skills.eyebrow": "Codex Skill 系统",
    "skills.title": "从未来设计方法到完整方案呈现的 AI Skill 套件",
    "skills.lede":
      "这套 skill 把课程工作流拆成一个总控大 skill 和多个可独立调用的小 skill。学生可以从未来信号开始一步步完成方法产物，也可以在方案完成后继续生成项目文档、PPT、效果图、交互原型、故事板、视频和本地项目档案。",
    "skills.controllerLabel": "总控入口",
    "skills.controllerDesc":
      "总控大 skill，负责串联完整 Future Design Thinking 流程：从主题界定、未来信号、STEEP、本地挑战、未来解释、Provotyping、明日头条、Backcasting，到最终方案和后期制作。",
    "skills.projectControllerLabel": "完整项目",
    "skills.projectControllerDesc":
      "项目级总控小 skill，负责把前期方法、后期呈现、资产归档和最终交付检查连成一个连续项目工作流。",
    "skills.phaseA": "方法探索",
    "skills.phaseADesc": "完成未来信号、STEEP、本地挑战、信号挑战配对、未来解释和概念卡。",
    "skills.phaseB": "未来叙事与路线",
    "skills.phaseBDesc": "把概念转化成可感知的未来新闻和可执行的倒推路线。",
    "skills.phaseC": "后期呈现制作",
    "skills.phaseCDesc": "根据项目类型推荐合适呈现组合，并调用文档、PPT、图片、原型、视频等制作 skill。",
    "skills.phaseD": "本地归档与交付",
    "skills.phaseDDesc": "把设计方法产物、生成资产、提示词、源文件和最终交付物保存到学生本地项目文件夹。",
    "skills.archiveEyebrow": "本地归档",
    "skills.archiveTitle": "每个学生都有一个结构化项目文件夹",
    "skills.archiveDesc":
      "skill 会把项目整理为 00_project-brief、01_method-process、03_visual-assets、04_prototypes、05_documents、06_presentations、07_video-audio、08_delivery 和 09_ai-process-log，确保过程、资产和最终提交都能被追踪。",
    "skills.downloadEyebrow": "下载",
    "skills.downloadTitle": "下载或安装这套 Skill",
    "skills.downloadDesc": "推荐整套下载，保留总控 skill 与小 skill 的调用关系；也可以打开单个 skill 查看它的 SKILL.md。",
    "skills.downloadZip": "下载完整 ZIP",
    "skills.openGithub": "打开 Skills 文件夹",
    "skills.installLabel": "Codex 安装命令",
    "skills.queryLabel": "快速验证 Query",
    "skills.query1": "列出我当前已安装的 Future Design 相关 skills。",
    "skills.query2": "用 future-design-project-controller 检查：如果主题是“北京中小学生 AI 教育”，你会按什么顺序带我完成？只列阶段名，不要生成方案。",
    "skills.query3": "用 future-signal-scout 为“北京中小学生 AI 教育”列 3 个未来信号标题即可，不要展开分析。",
    "skills.query4": "启动 Future Design Project Controller，模拟检查完整工作流是否可运行：列出每一步需要读取的上一步产物、会调用的 skill、会生成的产物名称。不要生成实际方案内容。",
    "skills.query5": "说明：这些 query 只用于验证安装、触发和调用链；完整方案仍需要按工作坊步骤逐步完成。",
    "outputs.eyebrow": "产出要求",
    "outputs.title": "AI 共创工作坊产出要求",
    "outputs.proto": "由未来信号和地方挑战组合形成，用于界定机会与冲突。",
    "outputs.interpretation": "用一句可讨论、可修改的未来解释串联 A、B、C 要素。",
    "outputs.headline": "以 2030/2040/2050 的新闻标题呈现可感知未来。",
    "outputs.backcasting": "以市长、商业领导者、个体行动者等角色倒推行动路径。",
    "support.eyebrow": "Technical Support",
    "support.title": "遇到问题？扫码联系我们",
    "support.desc": "如果在使用过程中遇到技术问题、Token 充值、API 配置等，可以通过微信扫码联系 manta.ai 获取帮助。",
    "support.scan": "微信扫码添加",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "工具使用",
    "toolsSection.codexDesc": "安装 Codex CLI 并配置 mantai LLM API 服务。",
    "toolsSection.skillDesc": "下载并安装设计工坊和多模态生成 Skill。",
    "toolsSection.verifyDesc": "验证 Skill 和 API 配置是否正常工作。",
  },
  en: {
    "nav.tracks": "Tracks",
    "nav.corpus": "Corpus",
    "nav.workshop": "Workshop",
    "nav.overview": "Overview",
    "nav.materials": "Materials",
    "nav.getStarted": "Get Started",
    "sidebar.title": "Documentation",
    "sidebar.intro": "About",
    "sidebar.tracksTime": "Tracks & Timeline",
    "sidebar.corpus": "Corpus Library",
    "sidebar.cases": "Case Library",
    "sidebar.workshop": "Workshop Flow",
    "sidebar.skills": "Skill System",
    "sidebar.outputs": "Outputs",
    "tools.codex": "Codex Setup",
    "tools.skills": "Skill Install",
    "tools.verify": "Verify Setup",
    "hero.eyebrow": "Space Art & Design Lab",
    "hero.title": "International Space Art & Design Collaborative Camp",
    "hero.subtitle": "Art and Design for Future Life in Space",
    "hero.lede":
      "From international co-creation and knowledge building to prototyping, review, exhibition, and continued incubation. The program translates space knowledge into understandable, perceptible, and experiential proposals for future life.",
    "hero.ctaTracks": "Explore Tracks",
    "hero.ctaWorkshop": "Workshop Flow",
    "hero.ctaSkills": "Skill System",
    "metric.tracks": "Tracks",
    "metric.tutors": "Tutors",
    "metric.regions": "Regions",
    "metric.institutions": "Institutions",
    "mission.eyebrow": "Mission",
    "mission.title": "Art and Design for Future Life in Space",
    "mission.callout":
      "The camp brings together leading international art and design schools with global aerospace experts. Through interdisciplinary collaboration, it connects space missions, extraterrestrial environments, future societies, and public experience into a future-civilization laboratory for creation, exhibition, and incubation.",
    "mission.knowledge": "Cross-disciplinary lectures build a shared knowledge base across aerospace, art, and design.",
    "mission.cocreation": "Cross-cultural teams develop concepts, prototypes, and exhibition plans across six directions.",
    "mission.exhibition": "Selected works enter a joint exhibition and form a panoramic narrative of futures in space.",
    "mission.validation": "Projects may continue into incubation and space-oriented or public-facing validation.",
    "tracks.eyebrow": "Six Tracks",
    "tracks.title": "Six paths into future life in space",
    "track1.title": "Space Vision & Future Narratives",
    "track1.desc": "Cultural payloads, mission narratives, science communication, and public participation",
    "track1.output": "Deliverables: digital narrative work, public interaction, exhibition carrier",
    "track2.title": "Space Habitation & Digital Construction",
    "track2.desc": "Martian polar habitation, digital construction, materials, and life-support systems",
    "track2.output": "Deliverables: system prototype, spatial carrier, interactive system",
    "track3.title": "Creative Payloads & Public Art",
    "track3.desc": "Public art under space environments and payload constraints",
    "track3.output": "Deliverables: core artwork, exhibition carrier, source and ethics record",
    "track4.title": "Off-Earth Daily Life & Experience Design",
    "track4.desc": "Dining, hygiene, rhythms, social connection, and recreation beyond Earth",
    "track4.output": "Deliverables: experience prototype, design dossier, concept video, panel",
    "track5.title": "Space Computing & Embodied Intelligence",
    "track5.desc": "Agents for cabin service, planetary exploration, and body augmentation",
    "track5.output": "Deliverables: physical prototype, visual proposal set, video, panel",
    "track6.title": "Space Fashion & Human-Machine Evolution",
    "track6.desc": "Clothing as the second skin between the body and an extraterrestrial world",
    "track6.output": "Deliverables: garment or wearable component, visual archive, video, panel",
    "timeline.eyebrow": "Program Rhythm",
    "timeline.title": "Three phases: knowledge, incubation, and exhibition",
    "timeline.phase1": "Phase 01",
    "timeline.phase1Title": "Expert Lectures & Knowledge Building",
    "timeline.phase1Desc": "Cross-disciplinary lectures build a shared language across aerospace, art, design, and technology.",
    "timeline.phase2": "Phase 02",
    "timeline.phase2Title": "Creative Exploration & Incubation",
    "timeline.phase2Desc": "Teams deepen concepts, test ideas, and form demonstrable prototypes.",
    "timeline.phase3": "Phase 03",
    "timeline.phase3Title": "Expert Review & Exhibition",
    "timeline.phase3Desc": "Roadshows, review, selection, and the joint exhibition support continued incubation.",
    "corpus.eyebrow": "Corpus Library",
    "corpus.title": "Four corpus packs provide future signals for concept generation",
    "corpus.viewDetails": "Open corpus page",
    "corpus1.title": "Corpus 1: Independent from Earth",
    "corpus1.short": "Independent from Earth",
    "corpus1.desc": "Key technology signals for long-term Mars settlement, from air, water, and power to ecological autonomy.",
    "corpus1.signals": "IE-01 to IE-30",
    "corpus1.use": "Life support, habitation systems, resource loops",
    "corpus2.title": "Corpus 2: Alien Mind",
    "corpus2.short": "Alien Mind",
    "corpus2.desc": "Psychological, physiological, and sensory alienation in space, used for emotional support and sensory intervention design.",
    "corpus2.signals": "AM-01 to AM-30",
    "corpus2.use": "Off-Earth daily life, experience design, space psychology",
    "corpus3.title": "Corpus 3: Hidden Twins",
    "corpus3.short": "Hidden Twins",
    "corpus3.desc": "A case library of aerospace technologies translated into everyday terrestrial products.",
    "corpus3.signals": "HT-01 to HT-30",
    "corpus3.use": "Product translation, material innovation, daily-life products",
    "corpus4.title": "Corpus 4: New Space Ritual Objects",
    "corpus4.short": "Space Ritual Objects",
    "corpus4.desc": "Symbolic, commemorative, and ritual meanings embedded in real space artifacts.",
    "corpus4.signals": "RS-01 to RS-33",
    "corpus4.use": "Cultural payloads, commemorative objects, space rituals",
    "cases.eyebrow": "Case Library",
    "cases.title": "Four themed case sets provide reference prototypes for design reasoning",
    "case1.title": "Case Library 1: Embodied Experience & Interaction Design",
    "case1.short": "Embodied Experience & Interaction",
    "case1.desc": "When bodily familiarity fails, how to rebuild the human–world connection through structured symbolic behavior.",
    "case1.signals": "EI-01 to EI-20",
    "case1.use": "Body–environment–material relations, perceptual design",
    "case2.title": "Case Library 2: Cultural Structure & Ritual Evolution",
    "case2.short": "Cultural Structure & Ritual",
    "case2.desc": "How to extend Earth's ritual structures and emotional codes into a spacefaring civilization.",
    "case2.signals": "CR-01 to CR-20",
    "case2.use": "Ritual structures, cultural systems, collective emotion",
    "case3.title": "Case Library 3: Time Reconstruction & Emotional Connection",
    "case3.short": "Time Reconstruction & Emotion",
    "case3.desc": "When circadian rhythm and seasons fail, how to rebuild emotion, memory, and ritual through design.",
    "case3.signals": "TE-01 to TE-17",
    "case3.use": "Time perception, emotion and memory design",
    "case4.title": "Case Library 4: Non-geographic Shared Space",
    "case4.short": "Non-geographic Shared Space",
    "case4.desc": "When space loses geographic meaning, how to build a sense of the public and of consensus.",
    "case4.signals": "NS-01 to NS-20",
    "case4.use": "Public sense, consensus systems, shared memory",
    "workshop.eyebrow": "AI Co-creation Workshop",
    "workshop.title": "Future Design Thinking Workflow",
    "workshop.step1": "Browse and select future signals.",
    "workshop.step2": "Select or enter local challenges, with AI-assisted expansion.",
    "workshop.step3": "Generate a Provotyping Card and an Interpretation sentence.",
    "workshop.step4": "Generate tomorrow's headline and scenario imagery.",
    "workshop.step5": "Backcast actions for 2040 and 2030 from a 2050 goal.",
    "skills.eyebrow": "Codex Skill System",
    "skills.title": "An AI skill suite from future design method to complete project presentation",
    "skills.lede":
      "This skill suite breaks the course workflow into one controller skill and multiple independently callable subskills. Students can move step by step from future signals to method outputs, then continue into reports, slides, visuals, interactive prototypes, storyboards, videos, and local project archives.",
    "skills.controllerLabel": "Controller",
    "skills.controllerDesc":
      "The main controller skill links the complete Future Design Thinking process: framing, future signals, STEEP, local challenge, interpretation, provotyping, tomorrow headline, backcasting, final proposal, and production.",
    "skills.projectControllerLabel": "Full Project",
    "skills.projectControllerDesc":
      "A project-level controller subskill that connects the method phase, production routing, asset archiving, and final delivery check into one continuous project workflow.",
    "skills.phaseA": "Method Exploration",
    "skills.phaseADesc": "Create future signals, STEEP, local challenge, signal-challenge pairing, interpretation, and concept card.",
    "skills.phaseB": "Future Narrative & Roadmap",
    "skills.phaseBDesc": "Turn the concept into a tangible future headline and an actionable backcasting route.",
    "skills.phaseC": "Production",
    "skills.phaseCDesc": "Recommend a fitting mix of deliverables and route into document, slide, image, prototype, and video skills.",
    "skills.phaseD": "Archive & Delivery",
    "skills.phaseDDesc": "Store method outputs, generated assets, prompts, source files, and final deliverables in each student's local project folder.",
    "skills.archiveEyebrow": "Local Archive",
    "skills.archiveTitle": "Each student keeps a structured project folder",
    "skills.archiveDesc":
      "The skills organize projects into 00_project-brief, 01_method-process, 03_visual-assets, 04_prototypes, 05_documents, 06_presentations, 07_video-audio, 08_delivery, and 09_ai-process-log so process, assets, and final submission remain traceable.",
    "skills.downloadEyebrow": "Download",
    "skills.downloadTitle": "Download or install this skill suite",
    "skills.downloadDesc": "Download the full suite to preserve the controller-to-subskill relationship, or open an individual skill to inspect its SKILL.md.",
    "skills.downloadZip": "Download ZIP",
    "skills.openGithub": "Open Skills Folder",
    "skills.installLabel": "Codex install command",
    "skills.queryLabel": "Quick validation queries",
    "skills.query1": "List the Future Design related skills currently installed.",
    "skills.query2": "Use future-design-project-controller to check: if my topic is AI education for primary and secondary students in Beijing, what sequence would you guide me through? List stage names only; do not generate a proposal.",
    "skills.query3": "Use future-signal-scout to list only 3 future signal titles for AI education for primary and secondary students in Beijing. Do not expand the analysis.",
    "skills.query4": "Start Future Design Project Controller and dry-run the full workflow: list what each step reads from the previous step, which skill it calls, and what artifact it creates. Do not generate actual proposal content.",
    "skills.query5": "Note: these queries only validate installation, triggering, and workflow routing. A complete proposal still needs to be completed step by step through the workshop.",
    "outputs.eyebrow": "Outputs",
    "outputs.title": "AI co-creation workshop outputs",
    "outputs.proto": "A combination of future signals and local challenges used to define opportunities and tensions.",
    "outputs.interpretation": "A discussable and editable sentence that connects the A, B, and C elements.",
    "outputs.headline": "A perceptible future presented as 2030, 2040, or 2050 news headlines.",
    "outputs.backcasting": "Action pathways backcast through roles such as mayor, business leader, and individual actor.",
    "support.eyebrow": "Technical Support",
    "support.title": "Need help? Scan to contact us",
    "support.desc": "For technical issues, token recharge, API configuration, or any other questions, scan the QR code to contact manta.ai via WeChat.",
    "support.scan": "Scan to add on WeChat",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "Tools & Setup",
    "toolsSection.codexDesc": "Install Codex CLI and configure the mantai LLM API service.",
    "toolsSection.skillDesc": "Download and install workshop and multimodal generation Skills.",
    "toolsSection.verifyDesc": "Verify that Skills and API configuration are working correctly.",

function applyLanguage(lang) {
  const current = translations[lang] ? lang : "zh";
  currentLanguage = current;

  document.documentElement.lang = current === "zh" ? "zh-CN" : "en";
  document.title =
    current === "zh"
      ? "国际太空艺术设计共创营"
      : "International Space Art & Design Collaborative Camp";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    const value = translations[current][key];
    if (value) element.textContent = value;
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.langSwitch === current;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("space-camp-language", current);
}

const observer = new IntersectionObserver(
  (entries) => {
    const visible = entries
      .filter((entry) => entry.isIntersecting)
      .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];

    if (!visible) return;

    sidebarLinks.forEach((link) => {
      link.classList.toggle("active", link.getAttribute("href") === `#${visible.target.id}`);
    });
  },
  {
    rootMargin: "-18% 0px -70% 0px",
    threshold: [0.1, 0.35, 0.6],
  },
);

sections.forEach((section) => observer.observe(section));

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.langSwitch));
});

applyLanguage(localStorage.getItem("space-camp-language") || "zh");
