const sections = [...document.querySelectorAll(".section[id]")];
const sidebarLinks = [...document.querySelectorAll(".sidebar a")];
const languageButtons = [...document.querySelectorAll("[data-lang-switch]")];
let currentLanguage = "zh";

const translations = {
  zh: {
    "nav.tracks": "赛道",
    "nav.corpus": "语料库",
    "nav.workshop": "工作坊",
    "nav.overview": "概览",
    "nav.materials": "素材",
    "nav.getStarted": "开始使用",
    "sidebar.title": "文档目录",
    "sidebar.intro": "项目介绍",
    "sidebar.tracksTime": "赛道与节奏",
    "sidebar.frictions": "痛点库",
    "sidebar.partners": "合作企业库",
    "frictions1.short": "5 大场景 · 15 条痛点",
    "partners1.short": "8 家养老具身智能企业",
    "sidebar.corpus": "语料库",
    "sidebar.cases": "案例库",
    "sidebar.workshop": "共创流程",
    "sidebar.skills": "Skill 系统",
    "sidebar.outputs": "产出要求",
    "sidebar.tools": "工具使用",
    "tools.course": "课程工具",
    "tools.skills": "Skill 安装",
    "tools.verify": "环境验证",
    "nav.home": "返回导航",
    "hero.eyebrow": "国家艺术基金 2026 · 具身智能养老共创营",
    "hero.title": "具身智能·未来养老共创营",
    "hero.subtitle": "Embodied Intelligence for Aging & Elderly Care Design Talent Program",
    "hero.lede":
      "面向深度老龄化社会的设计未来学项目。从设计未来学视角出发，把具身智能、陪护机器人与生成式人工智能转化为可理解、可感知、可落地的养老与适老化设计方案，面向全国遴选青年创意设计人才共创。",
    "hero.ctaTracks": "查看六大方向",
    "hero.ctaWorkshop": "查看工作坊流程",
    "hero.ctaSkills": "查看 Skill 系统",
    "metric.tracks": "教学方向",
    "metric.tutors": "授课嘉宾",
    "metric.regions": "全天课程",
    "metric.institutions": "遴选学员",
    "mission.eyebrow": "项目主旨",
    "mission.title": "以设计未来学回应老龄化时代的具身智能养老",
    "mission.callout":
      "本培训汇聚高校为主体、含行业一线的青年创意设计人才与 AI、设计、老年学、康养领域专家，通过跨学科协作，将具身智能、陪护机器人、适老化设计与公众体验连接成一个可创作、可展示、可落地转化的养老设计实验场。围绕《设计未来学视角下的人工智能创作逻辑》展开教学。",
    "mission.knowledge": "AIGC、设计与老年学跨界授课，建立共同知识底座。",
    "mission.cocreation": "青年设计人才围绕六个方向推进概念、原型与落地方案。",
    "mission.exhibition": "优秀成果进入成果展示，形成具身智能养老设计的全景叙事。",
    "mission.validation": "后续成果可继续孵化，并面向康养产业与公众传播验证。",
    "tracks.eyebrow": "六大方向",
    "tracks.title": "六条路径共同回答具身智能如何服务未来养老",
    "track1.title": "养老愿景与未来叙事",
    "track1.desc": "老龄社会想象、代际叙事、科普传播与公众参与",
    "track1.output": "交付：数字叙事作品、公众互动、传播载体",
    "track2.title": "具身智能与陪护机器人",
    "track2.desc": "陪护机器人、助行助浴、人机交互、触觉辅助与养老院具身系统",
    "track2.output": "交付：机器人原型、交互方案、具身系统设计",
    "track3.title": "适老化产品与交互设计",
    "track3.desc": "无障碍交互、语音助手、认知支持界面与多模态适老设计",
    "track3.output": "交付：产品方案、交互原型、可用性与伦理记录",
    "track4.title": "健康监测与智慧照护",
    "track4.desc": "可穿戴与环境感知、跌倒检测、步态与生命体征监测、远程照护",
    "track4.output": "交付：系统原型、监测装备方案、照护决策系统",
    "track5.title": "银发社区与服务设计",
    "track5.desc": "居家养老、社区嵌入式照护、适老服务与银发经济的智能表达",
    "track5.output": "交付：服务原型、视觉方案、视频、展板",
    "track6.title": "老年文化与可持续养老",
    "track6.desc": "老年数字素养、代际共融、康养文旅与可持续养老公共空间设计",
    "track6.output": "交付：设计作品、可视化档案、视频、展板",
    "timeline.eyebrow": "课程节奏",
    "timeline.title": "全天课程完成知识赋能、方法共创与成果孵化",
    "timeline.phase1": "阶段 01",
    "timeline.phase1Title": "专家授课与知识赋能",
    "timeline.phase1Desc": "跨学科授课建立 AIGC、设计、老年学与康养的共同语言。",
    "timeline.phase2": "阶段 02",
    "timeline.phase2Title": "创意探索与方案共创",
    "timeline.phase2Desc": "学员深化概念、完成试验并形成可展示的养老设计原型。",
    "timeline.phase3": "阶段 03",
    "timeline.phase3Title": "成果孵化与落地转化",
    "timeline.phase3Desc": "通过路演、点评、遴选与成果转化推进养老设计成果落地。",
    "frictions.eyebrow": "痛点库",
    "frictions.title": "五大场景十五条痛点，定位养老一线的真实需求",
    "frictions.mobilityTitle": "移乘：从床到轮椅的每一次转移",
    "frictions.mobilityDesc": "养老机构移乘辅助设备不足、居家与社区移乘障碍、移乘过程中的尊严损伤等一线痛点。",
    "frictions.mobilityRange": "FR-01 到 FR-03",
    "frictions.mobilityUse": "移乘 · Mobility",
    "frictions.dietTitle": "餐饮与营养：吃得下、吃得对",
    "frictions.dietDesc": "养老餐“不好吃、不想吃”、进食安全与吞咽风险、慢病膳食与营养失衡等痛点。",
    "frictions.dietRange": "FR-04 到 FR-09",
    "frictions.dietUse": "餐饮 · 营养",
    "frictions.careTitle": "照护与心理：身体照护之外的关怀",
    "frictions.careDesc": "日常照护负担、孤独与社会隔离、抑郁与认知症情感沟通等身心照护痛点。",
    "frictions.careRange": "FR-10 到 FR-15",
    "frictions.careUse": "照护 · 心理",
    "frictions.allTitle": "15 条痛点全景",
    "frictions.allDesc": "每条痛点含场景、痛点描述、真实案例、过渡方案、机会点与出处，可逐条展开查阅。",
    "partners.eyebrow": "合作企业库",
    "partners.title": "八家可对接的养老具身智能产业伙伴",
    "partners.frontierTitle": "具身前沿：整机与本体",
    "partners.frontierDesc": "星动纪元 ROBOTERA、北京具身智能机器人创新中心 X-Humanoid、银河通用 Galbot 等全栈人形与操作本体。",
    "partners.frontierRange": "PT-01 到 PT-03",
    "partners.frontierUse": "整机本体 · VLA 大模型",
    "partners.rehabTitle": "康复与服务落地",
    "partners.rehabDesc": "傅利叶 FOURIER 康复机器人、猎户星空 OrionStar 陪伴问询、云迹科技 Yunji 送物巡检等场景化产品。",
    "partners.rehabRange": "PT-04 到 PT-06",
    "partners.rehabUse": "康复 · 陪伴 · 配送",
    "partners.emergingTitle": "教育科研与消费级",
    "partners.emergingDesc": "加速进化 Booster、松延动力 Noetix 等面向教育科研与消费级的人形机器人整机方案。",
    "partners.emergingRange": "PT-07 到 PT-08",
    "partners.emergingUse": "教育科研 · 消费级",
    "partners.allTitle": "8 家企业全景",
    "partners.allDesc": "每家企业含优先级、代表能力、代表型号、能力矩阵、适用场景与官网，可逐条展开对接。",
    "corpus.eyebrow": "语料库",
    "corpus.title": "四组语料为概念生成提供具身智能养老设计信号",
    "corpus.viewDetails": "查看资料页",
    "corpus1.title": "语料包 1：具身智能与陪护机器人",
    "corpus1.short": "具身智能与陪护机器人",
    "corpus1.desc": "陪护机器人、助行助浴、人机交互、触觉辅助与养老具身系统的前沿研究信号。",
    "corpus1.signals": "ER-01 到 ER-09",
    "corpus1.use": "陪护机器人、具身交互、物理辅助",
    "corpus2.title": "语料包 2：健康监测与智慧照护",
    "corpus2.short": "健康监测与智慧照护",
    "corpus2.desc": "可穿戴与环境感知、跌倒检测、步态与生命体征监测、日常活动识别与远程照护信号。",
    "corpus2.signals": "HC-01 到 HC-09",
    "corpus2.use": "健康监测、智慧照护、风险预警",
    "corpus3.title": "语料包 3：适老化产品与交互设计",
    "corpus3.short": "适老化产品与交互设计",
    "corpus3.desc": "无障碍交互、老年语音助手、对话式智能体、认知支持界面与 AR/VR 适老设计信号。",
    "corpus3.signals": "AD-01 到 AD-09",
    "corpus3.use": "适老交互、认知支持、多模态设计",
    "corpus4.title": "语料包 4：养老愿景与 AI 陪伴",
    "corpus4.short": "养老愿景与 AI 陪伴",
    "corpus4.desc": "大模型陪伴、孤独与社会隔离干预、情感计算、居家养老与养老 AI 伦理信号。",
    "corpus4.signals": "CV-01 到 CV-10",
    "corpus4.use": "AI 陪伴、情感计算、养老伦理",
    "cases.eyebrow": "案例库",
    "cases.title": "四组议题案例为设计推演提供参考原型",
    "case1.title": "案例库 1：陪护机器人与具身系统",
    "case1.short": "陪护机器人与具身系统",
    "case1.desc": "陪护机器人、助行助浴与养老院具身系统的真实落地项目与企业实践。",
    "case1.signals": "SA-01 到 SA-06",
    "case1.use": "陪护机器人、具身系统、技术路径",
    "case2.title": "案例库 2：健康监测与照护平台",
    "case2.short": "健康监测与照护平台",
    "case2.desc": "跌倒检测、可穿戴监测、远程照护与智慧养老平台的真实案例。",
    "case2.signals": "BD-01 到 BD-06",
    "case2.use": "健康监测、照护平台、风险预警",
    "case3.title": "案例库 3：适老化产品与交互",
    "case3.short": "适老化产品与交互",
    "case3.desc": "老年语音助手、认知支持应用、无障碍交互与适老化改造的真实落地项目。",
    "case3.signals": "DV-01 到 DV-06",
    "case3.use": "适老产品、无障碍交互、认知支持",
    "case4.title": "案例库 4：银发社区与 AI 陪伴",
    "case4.short": "银发社区与 AI 陪伴",
    "case4.desc": "AI 陪伴、社区嵌入式养老、居家照护与代际共融的真实实践。",
    "case4.signals": "CS-01 到 CS-06",
    "case4.use": "AI 陪伴、社区养老、代际共融",
    "workshop.eyebrow": "AI 共创工作坊",
    "workshop.title": "Future Design Thinking 工作流",
    "workshop.step1": "浏览并选择未来信号。",
    "workshop.step2": "选择或输入养老挑战，AI 可辅助扩展。",
    "workshop.step3": "生成 Provotyping Card 与 Interpretation 句式。",
    "workshop.step4": "生成未来新闻标题和情境图像。",
    "workshop.step5": "从 2050 目标倒推 2040 与 2030 行动。",
    "skills.eyebrow": "Codex Skill 系统",
    "skills.title": "从未来设计方法到完整方案呈现的 AI Skill 套件",
    "skills.lede":
      "这套 skill 把课程工作流拆成一个总控大 skill 和多个可独立调用的小 skill。学生可以从未来信号开始一步步完成方法产物，也可以在方案完成后继续生成项目文档、PPT、效果图、交互原型、故事板、视频和本地项目档案。",
    "skills.controllerLabel": "总控入口",
    "skills.controllerDesc":
      "总控大 skill，负责串联完整 Future Design Thinking 流程：从主题界定、未来信号、STEEP、本地挑战、未来解释、Provotyping、明日头条、Backcasting，到最终方案和后期制作。",
    "skills.projectControllerLabel": "完整项目",
    "skills.projectControllerDesc":
      "项目级总控小 skill，负责把前期方法、后期呈现、资产归档和最终交付检查连成一个连续项目工作流。",
    "skills.phaseA": "方法探索",
    "skills.phaseADesc": "完成未来信号、STEEP、本地挑战、信号挑战配对、未来解释和概念卡。",
    "skills.phaseB": "未来叙事与路线",
    "skills.phaseBDesc": "把概念转化成可感知的未来新闻和可执行的倒推路线。",
    "skills.phaseC": "后期呈现制作",
    "skills.phaseCDesc": "根据项目类型推荐合适呈现组合，并调用文档、PPT、图片、原型、视频等制作 skill。",
    "skills.phaseD": "本地归档与交付",
    "skills.phaseDDesc": "把设计方法产物、生成资产、提示词、源文件和最终交付物保存到学生本地项目文件夹。",
    "skills.archiveEyebrow": "本地归档",
    "skills.archiveTitle": "每个学生都有一个结构化项目文件夹",
    "skills.archiveDesc":
      "skill 会把项目整理为 00_project-brief、01_method-process、03_visual-assets、04_prototypes、05_documents、06_presentations、07_video-audio、08_delivery 和 09_ai-process-log，确保过程、资产和最终提交都能被追踪。",
    "skills.downloadEyebrow": "下载",
    "skills.downloadTitle": "下载或安装这套 Skill",
    "skills.downloadDesc": "推荐整套下载，保留总控 skill 与小 skill 的调用关系；也可以打开单个 skill 查看它的 SKILL.md。",
    "skills.downloadZip": "下载完整 ZIP",
    "skills.openGithub": "打开 Skills 文件夹",
    "skills.installLabel": "Codex 安装命令",
    "skills.queryLabel": "快速验证 Query",
    "skills.query1": "列出我当前已安装的 Future Design 相关 skills。",
    "skills.query2": "用 future-design-project-controller 检查：如果主题是“社区嵌入式养老陪护机器人设计”，你会按什么顺序带我完成？只列阶段名，不要生成方案。",
    "skills.query3": "用 future-signal-scout 为“社区嵌入式养老陪护机器人设计”列 3 个未来信号标题即可，不要展开分析。",
    "skills.query4": "启动 Future Design Project Controller，模拟检查完整工作流是否可运行：列出每一步需要读取的上一步产物、会调用的 skill、会生成的产物名称。不要生成实际方案内容。",
    "skills.query5": "说明：这些 query 只用于验证安装、触发和调用链；完整方案仍需要按工作坊步骤逐步完成。",
    "outputs.eyebrow": "产出要求",
    "outputs.title": "AI 共创工作坊产出要求",
    "outputs.proto": "由未来信号和养老挑战组合形成，用于界定机会与冲突。",
    "outputs.interpretation": "用一句可讨论、可修改的未来解释串联 A、B、C 要素。",
    "outputs.headline": "以 2030/2040/2050 的新闻标题呈现可感知未来。",
    "outputs.backcasting": "以民政部门、康养企业、社区、家庭照护者等角色倒推行动路径。",
    "support.eyebrow": "Technical Support",
    "support.title": "遇到问题？扫码联系我们",
    "support.desc": "如果在使用过程中遇到技术问题、Token 充值、API 配置等，可以通过微信扫码联系 manta.ai 获取帮助。",
    "support.scan": "微信扫码添加",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "工具使用",
    "toolsSection.courseDesc": "进入 Agent Zero 在线课程，跟随引导完成 AI 工具的学习与配置。",
    "toolsSection.skillDesc": "下载并安装设计工坊和多模态生成 Skill。",
    "toolsSection.verifyDesc": "验证 Skill 和 API 配置是否正常工作。",
  },
  en: {
    "nav.tracks": "Tracks",
    "nav.corpus": "Corpus",
    "nav.workshop": "Workshop",
    "nav.overview": "Overview",
    "nav.materials": "Materials",
    "nav.getStarted": "Get Started",
    "sidebar.title": "Documentation",
    "sidebar.intro": "About",
    "sidebar.tracksTime": "Tracks & Timeline",
    "sidebar.frictions": "Pain Points",
    "sidebar.partners": "Partner Library",
    "frictions1.short": "5 Scenes · 15 Frictions",
    "partners1.short": "8 Eldercare Embodied-AI Firms",
    "sidebar.corpus": "Corpus Library",
    "sidebar.cases": "Case Library",
    "sidebar.workshop": "Workshop Flow",
    "sidebar.skills": "Skill System",
    "sidebar.outputs": "Outputs",
    "sidebar.tools": "Tools",
    "tools.course": "Course",
    "tools.skills": "Skill Install",
    "tools.verify": "Verify Setup",
    "nav.home": "Back to Hub",
    "hero.eyebrow": "National Art Fund 2026 · Embodied Intelligence for Elderly Care",
    "hero.title": "Embodied Intelligence · Future of Elderly Care Camp",
    "hero.subtitle": "Embodied Intelligence for Aging & Elderly Care Design Talent Program",
    "hero.lede":
      "A Future Design Lab program for a deeply aging society. From a Future Design Lab perspective, it turns embodied intelligence, companion robots, and generative AI into understandable, perceptible, and deployable design proposals for elderly care and age-friendly design, co-created by selected young creative designers nationwide.",
    "hero.ctaTracks": "Explore Tracks",
    "hero.ctaWorkshop": "Workshop Flow",
    "hero.ctaSkills": "Skill System",
    "metric.tracks": "Tracks",
    "metric.tutors": "Tutors",
    "metric.regions": "Full-day Course",
    "metric.institutions": "Selected Talents",
    "mission.eyebrow": "Mission",
    "mission.title": "Future Design Thinking for Embodied Elderly Care in an Aging Era",
    "mission.callout":
      "The program brings together young creative designers from universities and industry front lines with experts in AI, design, gerontology, and health-care. Through interdisciplinary collaboration, it connects embodied intelligence, companion robots, age-friendly design, and public experience into a design laboratory for creation, exhibition, and real-world transformation.",
    "mission.knowledge": "Cross-disciplinary lectures across AIGC, design, and gerontology build a shared knowledge base.",
    "mission.cocreation": "Young designers develop concepts, prototypes, and deployable plans across six directions.",
    "mission.exhibition": "Selected outcomes enter a showcase and form a panoramic narrative of embodied elderly-care design.",
    "mission.validation": "Outcomes may continue into incubation and validation with the health-care industry and the public.",
    "tracks.eyebrow": "Six Tracks",
    "tracks.title": "Six paths into how embodied intelligence serves the future of elderly care",
    "track1.title": "Aging Vision & Future Narratives",
    "track1.desc": "Aging-society imagination, intergenerational narratives, science communication, and public participation",
    "track1.output": "Deliverables: digital narrative work, public interaction, communication carrier",
    "track2.title": "Embodied Intelligence & Companion Robots",
    "track2.desc": "Companion robots, mobility/bathing assistance, human-robot interaction, tactile assistance, embodied care systems",
    "track2.output": "Deliverables: robot prototype, interaction proposal, embodied system design",
    "track3.title": "Age-friendly Products & Interaction Design",
    "track3.desc": "Accessible interaction, voice assistants, cognitive-support interfaces, and multimodal age-friendly design",
    "track3.output": "Deliverables: product proposal, interaction prototype, usability & ethics record",
    "track4.title": "Health Monitoring & Smart Care",
    "track4.desc": "Wearable/ambient sensing, fall detection, gait & vital-sign monitoring, and remote care",
    "track4.output": "Deliverables: system prototype, monitoring equipment proposal, care decision system",
    "track5.title": "Silver Community & Service Design",
    "track5.desc": "Intelligent expression of aging-in-place, community-embedded care, age-friendly services, and the silver economy",
    "track5.output": "Deliverables: service prototype, visual proposal, video, panel",
    "track6.title": "Elder Culture & Sustainable Aging",
    "track6.desc": "Digital literacy for elders, intergenerational integration, health tourism, and sustainable aging public space",
    "track6.output": "Deliverables: design work, visualization archive, video, panel",
    "timeline.eyebrow": "Program Rhythm",
    "timeline.title": "A full-day course for knowledge, co-creation, and incubation",
    "timeline.phase1": "Phase 01",
    "timeline.phase1Title": "Expert Lectures & Knowledge Building",
    "timeline.phase1Desc": "Cross-disciplinary lectures build a shared language across AIGC, design, gerontology, and elderly care.",
    "timeline.phase2": "Phase 02",
    "timeline.phase2Title": "Creative Exploration & Co-creation",
    "timeline.phase2Desc": "Learners deepen concepts, test ideas, and form demonstrable elderly-care design prototypes.",
    "timeline.phase3": "Phase 03",
    "timeline.phase3Title": "Incubation & Real-world Transformation",
    "timeline.phase3Desc": "Roadshows, review, selection, and outcome transformation drive elderly-care design into practice.",
    "frictions.eyebrow": "Pain Points",
    "frictions.title": "Five scenes, fifteen frictions — pinpointing real eldercare needs",
    "frictions.mobilityTitle": "Mobility: every transfer from bed to wheelchair",
    "frictions.mobilityDesc": "Shortage of transfer aids in care homes, mobility barriers at home and in communities, and dignity harm during transfers.",
    "frictions.mobilityRange": "FR-01 to FR-03",
    "frictions.mobilityUse": "Mobility",
    "frictions.dietTitle": "Dining & nutrition: eating enough, eating right",
    "frictions.dietDesc": "\u201CUnappetizing, no appetite\u201D eldercare meals, feeding safety and swallowing risks, chronic-disease diets and nutritional imbalance.",
    "frictions.dietRange": "FR-04 to FR-09",
    "frictions.dietUse": "Dining · Nutrition",
    "frictions.careTitle": "Care & psychology: beyond the body",
    "frictions.careDesc": "Daily care burden, loneliness and social isolation, depression and emotional communication in dementia.",
    "frictions.careRange": "FR-10 to FR-15",
    "frictions.careUse": "Care · Psychology",
    "frictions.allTitle": "All 15 frictions",
    "frictions.allDesc": "Each friction includes scene, description, real case, transitional solution, opportunity and source — expand to read.",
    "partners.eyebrow": "Partner Library",
    "partners.title": "Eight embodied-AI industry partners ready for eldercare collaboration",
    "partners.frontierTitle": "Embodied frontier: full robots & bodies",
    "partners.frontierDesc": "ROBOTERA, X-Humanoid and Galbot — full-stack humanoids and manipulation platforms.",
    "partners.frontierRange": "PT-01 to PT-03",
    "partners.frontierUse": "Whole robot · VLA models",
    "partners.rehabTitle": "Rehabilitation & service deployment",
    "partners.rehabDesc": "Fourier rehab robots, OrionStar companionship, Yunji delivery and inspection — scene-ready products.",
    "partners.rehabRange": "PT-04 to PT-06",
    "partners.rehabUse": "Rehab · Companion · Delivery",
    "partners.emergingTitle": "Research & consumer grade",
    "partners.emergingDesc": "Booster and Noetix — humanoid platforms for research, education and consumer applications.",
    "partners.emergingRange": "PT-07 to PT-08",
    "partners.emergingUse": "Research · Consumer",
    "partners.allTitle": "All 8 companies",
    "partners.allDesc": "Each company includes priority, key capability, flagship model, capability matrix, use cases and website — expand to connect.",
    "corpus.eyebrow": "Corpus Library",
    "corpus.title": "Four corpus packs provide embodied elderly-care signals for concept generation",
    "corpus.viewDetails": "Open corpus page",
    "corpus1.title": "Corpus 1: Embodied Intelligence & Companion Robots",
    "corpus1.short": "Embodied Intelligence & Companion Robots",
    "corpus1.desc": "Frontier research signals on companion robots, mobility/bathing assistance, human-robot interaction, tactile assistance, and embodied care systems.",
    "corpus1.signals": "ER-01 to ER-09",
    "corpus1.use": "Companion robots, embodied interaction, physical assistance",
    "corpus2.title": "Corpus 2: Health Monitoring & Smart Care",
    "corpus2.short": "Health Monitoring & Smart Care",
    "corpus2.desc": "Signals on wearable/ambient sensing, fall detection, gait & vital-sign monitoring, activity recognition, and remote care.",
    "corpus2.signals": "HC-01 to HC-09",
    "corpus2.use": "Health monitoring, smart care, risk alerting",
    "corpus3.title": "Corpus 3: Age-friendly Products & Interaction Design",
    "corpus3.short": "Age-friendly Products & Interaction Design",
    "corpus3.desc": "Signals on accessible interaction, senior voice assistants, conversational agents, cognitive-support interfaces, and AR/VR age-friendly design.",
    "corpus3.signals": "AD-01 to AD-09",
    "corpus3.use": "Age-friendly interaction, cognitive support, multimodal design",
    "corpus4.title": "Corpus 4: Aging Vision & AI Companionship",
    "corpus4.short": "Aging Vision & AI Companionship",
    "corpus4.desc": "Signals on LLM-based companionship, loneliness/social-isolation intervention, affective computing, aging-in-place, and elderly-care AI ethics.",
    "corpus4.signals": "CV-01 to CV-10",
    "corpus4.use": "AI companionship, affective computing, care ethics",
    "cases.eyebrow": "Case Library",
    "cases.title": "Four themed case sets provide reference prototypes for design reasoning",
    "case1.title": "Case Library 1: Companion Robots & Embodied Systems",
    "case1.short": "Companion Robots & Embodied Systems",
    "case1.desc": "Real deployed projects and enterprise practices in companion robots, mobility/bathing assistance, and embodied care systems.",
    "case1.signals": "SA-01 to SA-06",
    "case1.use": "Companion robots, embodied systems, tech pathways",
    "case2.title": "Case Library 2: Health Monitoring & Care Platforms",
    "case2.short": "Health Monitoring & Care Platforms",
    "case2.desc": "Real cases in fall detection, wearable monitoring, remote care, and smart elderly-care platforms.",
    "case2.signals": "BD-01 to BD-06",
    "case2.use": "Health monitoring, care platforms, risk alerting",
    "case3.title": "Case Library 3: Age-friendly Products & Interaction",
    "case3.short": "Age-friendly Products & Interaction",
    "case3.desc": "Real deployed projects in senior voice assistants, cognitive-support apps, accessible interaction, and age-friendly retrofits.",
    "case3.signals": "DV-01 to DV-06",
    "case3.use": "Age-friendly products, accessible interaction, cognitive support",
    "case4.title": "Case Library 4: Silver Community & AI Companionship",
    "case4.short": "Silver Community & AI Companionship",
    "case4.desc": "Real practices in AI companionship, community-embedded care, home care, and intergenerational integration.",
    "case4.signals": "CS-01 to CS-06",
    "case4.use": "AI companionship, community care, intergenerational integration",
    "workshop.eyebrow": "AI Co-creation Workshop",
    "workshop.title": "Future Design Thinking Workflow",
    "workshop.step1": "Browse and select future signals.",
    "workshop.step2": "Select or enter elderly-care challenges, with AI-assisted expansion.",
    "workshop.step3": "Generate a Provotyping Card and an Interpretation sentence.",
    "workshop.step4": "Generate tomorrow's headline and scenario imagery.",
    "workshop.step5": "Backcast actions for 2040 and 2030 from a 2050 goal.",
    "skills.eyebrow": "Codex Skill System",
    "skills.title": "An AI skill suite from future design method to complete project presentation",
    "skills.lede":
      "This skill suite breaks the course workflow into one controller skill and multiple independently callable subskills. Students can move step by step from future signals to method outputs, then continue into reports, slides, visuals, interactive prototypes, storyboards, videos, and local project archives.",
    "skills.controllerLabel": "Controller",
    "skills.controllerDesc":
      "The main controller skill links the complete Future Design Thinking process: framing, future signals, STEEP, local challenge, interpretation, provotyping, tomorrow headline, backcasting, final proposal, and production.",
    "skills.projectControllerLabel": "Full Project",
    "skills.projectControllerDesc":
      "A project-level controller subskill that connects the method phase, production routing, asset archiving, and final delivery check into one continuous project workflow.",
    "skills.phaseA": "Method Exploration",
    "skills.phaseADesc": "Create future signals, STEEP, local challenge, signal-challenge pairing, interpretation, and concept card.",
    "skills.phaseB": "Future Narrative & Roadmap",
    "skills.phaseBDesc": "Turn the concept into a tangible future headline and an actionable backcasting route.",
    "skills.phaseC": "Production",
    "skills.phaseCDesc": "Recommend a fitting mix of deliverables and route into document, slide, image, prototype, and video skills.",
    "skills.phaseD": "Archive & Delivery",
    "skills.phaseDDesc": "Store method outputs, generated assets, prompts, source files, and final deliverables in each student's local project folder.",
    "skills.archiveEyebrow": "Local Archive",
    "skills.archiveTitle": "Each student keeps a structured project folder",
    "skills.archiveDesc":
      "The skills organize projects into 00_project-brief, 01_method-process, 03_visual-assets, 04_prototypes, 05_documents, 06_presentations, 07_video-audio, 08_delivery, and 09_ai-process-log so process, assets, and final submission remain traceable.",
    "skills.downloadEyebrow": "Download",
    "skills.downloadTitle": "Download or install this skill suite",
    "skills.downloadDesc": "Download the full suite to preserve the controller-to-subskill relationship, or open an individual skill to inspect its SKILL.md.",
    "skills.downloadZip": "Download ZIP",
    "skills.openGithub": "Open Skills Folder",
    "skills.installLabel": "Codex install command",
    "skills.queryLabel": "Quick validation queries",
    "skills.query1": "List the Future Design related skills currently installed.",
    "skills.query2": "Use future-design-project-controller to check: if my topic is community-embedded elderly-care companion robot design, what sequence would you guide me through? List stage names only; do not generate a proposal.",
    "skills.query3": "Use future-signal-scout to list only 3 future signal titles for community-embedded elderly-care companion robot design. Do not expand the analysis.",
    "skills.query4": "Start Future Design Project Controller and dry-run the full workflow: list what each step reads from the previous step, which skill it calls, and what artifact it creates. Do not generate actual proposal content.",
    "skills.query5": "Note: these queries only validate installation, triggering, and workflow routing. A complete proposal still needs to be completed step by step through the workshop.",
    "outputs.eyebrow": "Outputs",
    "outputs.title": "AI co-creation workshop outputs",
    "outputs.proto": "A combination of future signals and elderly-care challenges used to define opportunities and tensions.",
    "outputs.interpretation": "A discussable and editable sentence that connects the A, B, and C elements.",
    "outputs.headline": "A perceptible future presented as 2030, 2040, or 2050 news headlines.",
    "outputs.backcasting": "Action pathways backcast through roles such as civil-affairs authority, health-care enterprise, community, and family caregiver.",
    "support.eyebrow": "Technical Support",
    "support.title": "Need help? Scan to contact us",
    "support.desc": "For technical issues, token recharge, API configuration, or any other questions, scan the QR code to contact manta.ai via WeChat.",
    "support.scan": "Scan to add on WeChat",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "Tools & Setup",
    "toolsSection.courseDesc": "Open the Agent Zero online course and follow the guided steps to learn and set up AI tools.",
    "toolsSection.skillDesc": "Download and install workshop and multimodal generation Skills.",
    "toolsSection.verifyDesc": "Verify that Skills and API configuration are working correctly.",
  },
};

function applyLanguage(lang) {
  const current = translations[lang] ? lang : "zh";
  currentLanguage = current;

  document.documentElement.lang = current === "zh" ? "zh-CN" : "en";
  document.title =
    current === "zh"
      ? "具身智能·未来养老共创营 · 国家艺术基金 2026"
      : "Embodied Intelligence Elderly Care Co-Creation Camp · National Art Fund 2026";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    const value = translations[current][key];
    if (value) element.textContent = value;
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.langSwitch === current;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("care-camp-language", current);
}

const observer = new IntersectionObserver(
  (entries) => {
    const visible = entries
      .filter((entry) => entry.isIntersecting)
      .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];

    if (!visible) return;

    sidebarLinks.forEach((link) => {
      link.classList.toggle("active", link.getAttribute("href") === `#${visible.target.id}`);
    });
  },
  {
    rootMargin: "-18% 0px -70% 0px",
    threshold: [0.1, 0.35, 0.6],
  },
);

sections.forEach((section) => observer.observe(section));

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.langSwitch));
});

applyLanguage(localStorage.getItem("care-camp-language") || "zh");
