const sections = [...document.querySelectorAll(".section[id]")];
const sidebarLinks = [...document.querySelectorAll(".sidebar a")];
const languageButtons = [...document.querySelectorAll("[data-lang-switch]")];
let currentLanguage = "zh";

const translations = {
  zh: {
    "nav.tracks": "赛道",
    "nav.corpus": "语料库",
    "nav.workshop": "工作坊",
    "nav.overview": "概览",
    "nav.materials": "素材",
    "nav.getStarted": "开始使用",
    "sidebar.title": "文档目录",
    "sidebar.intro": "项目介绍",
    "sidebar.tracksTime": "赛道与节奏",
    "sidebar.corpus": "语料库",
    "sidebar.cases": "案例库",
    "sidebar.workshop": "共创流程",
    "sidebar.skills": "Skill 系统",
    "sidebar.outputs": "产出要求",
    "sidebar.tools": "工具使用",
    "tools.codex": "Codex 配置",
    "tools.skills": "Skill 安装",
    "tools.verify": "环境验证",
    "hero.eyebrow": "生成式AI助农设计人才培训",
    "hero.title": "国家农业科技创新港·生成式人工智能助农设计人才培训",
    "hero.subtitle": "Generative AI for Rural Revitalization Design Talent Program",
    "hero.lede":
      "2026 年度国家艺术基金项目。从设计未来学视角出发，把生成式人工智能转化为可理解、可感知、可落地的乡村振兴与助农设计方案，面向全国遴选青年创意设计人才共创。",
    "hero.ctaTracks": "查看六大方向",
    "hero.ctaWorkshop": "查看工作坊流程",
    "hero.ctaSkills": "查看 Skill 系统",
    "metric.tracks": "教学方向",
    "metric.tutors": "授课嘉宾",
    "metric.regions": "全天课程",
    "metric.institutions": "遴选学员",
    "mission.eyebrow": "项目主旨",
    "mission.title": "以设计未来学回应生成式AI时代的乡村振兴",
    "mission.callout":
      "本培训汇聚高校为主体、含行业一线的青年创意设计人才与 AI、设计、农业领域专家，通过跨学科协作，将生成式人工智能、乡村产业、地方文化与公众体验连接成一个可创作、可展示、可落地转化的助农设计实验场。围绕《设计未来学视角下的人工智能创作逻辑》展开教学。",
    "mission.knowledge": "AIGC、设计与农业跨界授课，建立共同知识底座。",
    "mission.cocreation": "青年设计人才围绕六个方向推进概念、原型与落地方案。",
    "mission.exhibition": "优秀成果进入成果展示，形成乡村振兴设计的全景叙事。",
    "mission.validation": "后续成果可继续孵化，并面向乡村产业与公众传播验证。",
    "tracks.eyebrow": "六大方向",
    "tracks.title": "六条路径共同回答生成式AI如何助农兴村",
    "track1.title": "乡村愿景与未来叙事",
    "track1.desc": "地方文化、产业叙事、科普传播与公众参与",
    "track1.output": "交付：数字叙事作品、公众互动、传播载体",
    "track2.title": "智慧农业与数字生产",
    "track2.desc": "AI 育种、遥感监测、无人农场、农业大模型与病虫害识别",
    "track2.output": "交付：系统原型、智能装备方案、决策系统",
    "track3.title": "农产品品牌与文创设计",
    "track3.desc": "AIGC 驱动的农产品品牌、包装、IP 与视觉体系",
    "track3.output": "交付：品牌方案、包装/IP、来源与伦理记录",
    "track4.title": "乡村生活与体验设计",
    "track4.desc": "文旅、节庆、社区、服务与日常的乡村生活体验原型",
    "track4.output": "交付：体验原型、设计档案、概念视频、展板",
    "track5.title": "数字乡村与助农平台",
    "track5.desc": "农村电商、直播助农、供应链溯源与智慧治理的智能表达",
    "track5.output": "交付：平台原型、视觉方案、视频、展板",
    "track6.title": "乡村文化与可持续设计",
    "track6.desc": "非遗活化、生态农业、碳中和与乡村公共空间的设计探索",
    "track6.output": "交付：设计作品、可视化档案、视频、展板",
    "timeline.eyebrow": "课程节奏",
    "timeline.title": "全天课程完成知识赋能、方法共创与成果孵化",
    "timeline.phase1": "阶段 01",
    "timeline.phase1Title": "专家授课与知识赋能",
    "timeline.phase1Desc": "跨学科授课建立 AIGC、设计、农业与乡村振兴的共同语言。",
    "timeline.phase2": "阶段 02",
    "timeline.phase2Title": "创意探索与方案共创",
    "timeline.phase2Desc": "学员深化概念、完成试验并形成可展示的助农设计原型。",
    "timeline.phase3": "阶段 03",
    "timeline.phase3Title": "成果孵化与落地转化",
    "timeline.phase3Desc": "通过路演、点评、遴选与成果转化推进农业设计成果落地。",
    "corpus.eyebrow": "语料库",
    "corpus.title": "四组语料为概念生成提供助农设计信号",
    "corpus.viewDetails": "查看资料页",
    "corpus1.title": "语料包 1：智慧农业与生产技术",
    "corpus1.short": "智慧农业与生产技术",
    "corpus1.desc": "AI 育种、遥感监测、无人农场、农业大模型与病虫害识别等生产技术信号。",
    "corpus1.signals": "AG-01 到 AG-30",
    "corpus1.use": "智慧生产、精准农业、农业智能",
    "corpus2.title": "语料包 2：乡村品牌与文创",
    "corpus2.short": "乡村品牌与文创",
    "corpus2.desc": "AIGC 生成式设计、农产品品牌包装、乡村 IP 孵化与短视频直播助农信号。",
    "corpus2.signals": "CB-01 到 CB-20",
    "corpus2.use": "品牌文创、IP 孵化、内容营销",
    "corpus3.title": "语料包 3：数字乡村与平台",
    "corpus3.short": "数字乡村与平台",
    "corpus3.desc": "农村电商、供应链溯源、数字普惠金融、智慧治理与乡村数据基础设施信号。",
    "corpus3.signals": "DR-01 到 DR-20",
    "corpus3.use": "数字乡村、平台经济、智慧治理",
    "corpus4.title": "语料包 4：乡村文化与可持续",
    "corpus4.short": "乡村文化与可持续",
    "corpus4.desc": "非遗民艺数字化、乡村文旅体验、生态农业碳中和与公共空间设计信号。",
    "corpus4.signals": "CH-01 到 CH-20",
    "corpus4.use": "文化活化、生态可持续、社区设计",
    "cases.eyebrow": "案例库",
    "cases.title": "四组议题案例为设计推演提供参考原型",
    "case1.title": "案例库 1：智慧农业与 AI 生产",
    "case1.short": "智慧农业与 AI 生产",
    "case1.desc": "AI 育种、无人农场、农业大模型与智能识别等真实落地项目与企业实践。",
    "case1.signals": "SA-01 到 SA-18",
    "case1.use": "智慧生产、精准农业、技术路径",
    "case2.title": "案例库 2：乡村品牌与 AIGC 文创",
    "case2.short": "乡村品牌与 AIGC 文创",
    "case2.desc": "农产品品牌设计、乡村 IP、AIGC 包装海报与短视频营销的真实案例。",
    "case2.signals": "BD-01 到 BD-18",
    "case2.use": "品牌设计、IP 孵化、内容营销",
    "case3.title": "案例库 3：数字乡村与平台",
    "case3.short": "数字乡村与平台",
    "case3.desc": "农村电商、数字治理、溯源与智慧文旅平台的真实落地项目。",
    "case3.signals": "DV-01 到 DV-18",
    "case3.use": "数字乡村、平台经济、公共服务",
    "case4.title": "案例库 4：乡村文化与可持续设计",
    "case4.short": "乡村文化与可持续设计",
    "case4.desc": "非遗活化、乡村公共空间、生态农业与社区设计的真实实践。",
    "case4.signals": "CS-01 到 CS-18",
    "case4.use": "文化活化、可持续、社区营造",
    "workshop.eyebrow": "AI 共创工作坊",
    "workshop.title": "Future Design Thinking 工作流",
    "workshop.step1": "浏览并选择未来信号。",
    "workshop.step2": "选择或输入地方挑战，AI 可辅助扩展。",
    "workshop.step3": "生成 Provotyping Card 与 Interpretation 句式。",
    "workshop.step4": "生成未来新闻标题和情境图像。",
    "workshop.step5": "从 2050 目标倒推 2040 与 2030 行动。",
    "skills.eyebrow": "Codex Skill 系统",
    "skills.title": "从未来设计方法到完整方案呈现的 AI Skill 套件",
    "skills.lede":
      "这套 skill 把课程工作流拆成一个总控大 skill 和多个可独立调用的小 skill。学生可以从未来信号开始一步步完成方法产物，也可以在方案完成后继续生成项目文档、PPT、效果图、交互原型、故事板、视频和本地项目档案。",
    "skills.controllerLabel": "总控入口",
    "skills.controllerDesc":
      "总控大 skill，负责串联完整 Future Design Thinking 流程：从主题界定、未来信号、STEEP、本地挑战、未来解释、Provotyping、明日头条、Backcasting，到最终方案和后期制作。",
    "skills.projectControllerLabel": "完整项目",
    "skills.projectControllerDesc":
      "项目级总控小 skill，负责把前期方法、后期呈现、资产归档和最终交付检查连成一个连续项目工作流。",
    "skills.phaseA": "方法探索",
    "skills.phaseADesc": "完成未来信号、STEEP、本地挑战、信号挑战配对、未来解释和概念卡。",
    "skills.phaseB": "未来叙事与路线",
    "skills.phaseBDesc": "把概念转化成可感知的未来新闻和可执行的倒推路线。",
    "skills.phaseC": "后期呈现制作",
    "skills.phaseCDesc": "根据项目类型推荐合适呈现组合，并调用文档、PPT、图片、原型、视频等制作 skill。",
    "skills.phaseD": "本地归档与交付",
    "skills.phaseDDesc": "把设计方法产物、生成资产、提示词、源文件和最终交付物保存到学生本地项目文件夹。",
    "skills.archiveEyebrow": "本地归档",
    "skills.archiveTitle": "每个学生都有一个结构化项目文件夹",
    "skills.archiveDesc":
      "skill 会把项目整理为 00_project-brief、01_method-process、03_visual-assets、04_prototypes、05_documents、06_presentations、07_video-audio、08_delivery 和 09_ai-process-log，确保过程、资产和最终提交都能被追踪。",
    "skills.downloadEyebrow": "下载",
    "skills.downloadTitle": "下载或安装这套 Skill",
    "skills.downloadDesc": "推荐整套下载，保留总控 skill 与小 skill 的调用关系；也可以打开单个 skill 查看它的 SKILL.md。",
    "skills.downloadZip": "下载完整 ZIP",
    "skills.openGithub": "打开 Skills 文件夹",
    "skills.installLabel": "Codex 安装命令",
    "skills.queryLabel": "快速验证 Query",
    "skills.query1": "列出我当前已安装的 Future Design 相关 skills。",
    "skills.query2": "用 future-design-project-controller 检查：如果主题是“县域农产品品牌与助农设计”，你会按什么顺序带我完成？只列阶段名，不要生成方案。",
    "skills.query3": "用 future-signal-scout 为“县域农产品品牌与助农设计”列 3 个未来信号标题即可，不要展开分析。",
    "skills.query4": "启动 Future Design Project Controller，模拟检查完整工作流是否可运行：列出每一步需要读取的上一步产物、会调用的 skill、会生成的产物名称。不要生成实际方案内容。",
    "skills.query5": "说明：这些 query 只用于验证安装、触发和调用链；完整方案仍需要按工作坊步骤逐步完成。",
    "outputs.eyebrow": "产出要求",
    "outputs.title": "AI 共创工作坊产出要求",
    "outputs.proto": "由未来信号和地方挑战组合形成，用于界定机会与冲突。",
    "outputs.interpretation": "用一句可讨论、可修改的未来解释串联 A、B、C 要素。",
    "outputs.headline": "以 2030/2040/2050 的新闻标题呈现可感知未来。",
    "outputs.backcasting": "以县长、企业负责人、个体行动者等角色倒推行动路径。",
    "support.eyebrow": "Technical Support",
    "support.title": "遇到问题？扫码联系我们",
    "support.desc": "如果在使用过程中遇到技术问题、Token 充值、API 配置等，可以通过微信扫码联系 manta.ai 获取帮助。",
    "support.scan": "微信扫码添加",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "工具使用",
    "toolsSection.codexDesc": "安装 Codex CLI 并配置 mantai LLM API 服务。",
    "toolsSection.skillDesc": "下载并安装设计工坊和多模态生成 Skill。",
    "toolsSection.verifyDesc": "验证 Skill 和 API 配置是否正常工作。",
  },
  en: {
    "nav.tracks": "Tracks",
    "nav.corpus": "Corpus",
    "nav.workshop": "Workshop",
    "nav.overview": "Overview",
    "nav.materials": "Materials",
    "nav.getStarted": "Get Started",
    "sidebar.title": "Documentation",
    "sidebar.intro": "About",
    "sidebar.tracksTime": "Tracks & Timeline",
    "sidebar.corpus": "Corpus Library",
    "sidebar.cases": "Case Library",
    "sidebar.workshop": "Workshop Flow",
    "sidebar.skills": "Skill System",
    "sidebar.outputs": "Outputs",
    "sidebar.tools": "Tools",
    "tools.codex": "Codex Setup",
    "tools.skills": "Skill Install",
    "tools.verify": "Verify Setup",
    "hero.eyebrow": "Generative AI for Rural Design Talent",
    "hero.title": "Generative AI for Rural Revitalization Design Talent Program",
    "hero.subtitle": "National Agricultural Sci-Tech Innovation Port · 2026 National Arts Fund Program",
    "hero.lede":
      "A 2026 National Arts Fund program. From a Future Design Lab perspective, it turns generative AI into understandable, perceptible, and deployable design proposals for rural revitalization, co-created by selected young creative designers nationwide.",
    "hero.ctaTracks": "Explore Tracks",
    "hero.ctaWorkshop": "Workshop Flow",
    "hero.ctaSkills": "Skill System",
    "metric.tracks": "Tracks",
    "metric.tutors": "Tutors",
    "metric.regions": "Full-day Course",
    "metric.institutions": "Selected Talents",
    "mission.eyebrow": "Mission",
    "mission.title": "Future Design Thinking for Rural Revitalization in the Generative AI Era",
    "mission.callout":
      "The program brings together young creative designers from universities and industry front lines with experts in AI, design, and agriculture. Through interdisciplinary collaboration, it connects generative AI, rural industries, local culture, and public experience into a design laboratory for creation, exhibition, and real-world transformation.",
    "mission.knowledge": "Cross-disciplinary lectures across AIGC, design, and agriculture build a shared knowledge base.",
    "mission.cocreation": "Young designers develop concepts, prototypes, and deployable plans across six directions.",
    "mission.exhibition": "Selected outcomes enter a showcase and form a panoramic narrative of rural revitalization design.",
    "mission.validation": "Outcomes may continue into incubation and validation with rural industries and the public.",
    "tracks.eyebrow": "Six Tracks",
    "tracks.title": "Six paths into how generative AI serves rural revitalization",
    "track1.title": "Rural Vision & Future Narratives",
    "track1.desc": "Local culture, industry narratives, science communication, and public participation",
    "track1.output": "Deliverables: digital narrative work, public interaction, communication carrier",
    "track2.title": "Smart Agriculture & Digital Production",
    "track2.desc": "AI breeding, remote sensing, autonomous farms, agri foundation models, and pest recognition",
    "track2.output": "Deliverables: system prototype, intelligent equipment proposal, decision system",
    "track3.title": "Agri-product Brand & Cultural-creative Design",
    "track3.desc": "AIGC-driven agri-product brands, packaging, IP, and visual systems",
    "track3.output": "Deliverables: brand proposal, packaging/IP, source and ethics record",
    "track4.title": "Rural Life & Experience Design",
    "track4.desc": "Rural life experience prototypes for tourism, festivals, community, service, and daily life",
    "track4.output": "Deliverables: experience prototype, design dossier, concept video, panel",
    "track5.title": "Digital Village & Rural Platforms",
    "track5.desc": "Intelligent expression of rural e-commerce, live-commerce, supply-chain traceability, and smart governance",
    "track5.output": "Deliverables: platform prototype, visual proposal, video, panel",
    "track6.title": "Rural Culture & Sustainable Design",
    "track6.desc": "Design explorations of heritage revival, eco-agriculture, carbon neutrality, and rural public space",
    "track6.output": "Deliverables: design work, visualization archive, video, panel",
    "timeline.eyebrow": "Program Rhythm",
    "timeline.title": "A full-day course for knowledge, co-creation, and incubation",
    "timeline.phase1": "Phase 01",
    "timeline.phase1Title": "Expert Lectures & Knowledge Building",
    "timeline.phase1Desc": "Cross-disciplinary lectures build a shared language across AIGC, design, agriculture, and rural revitalization.",
    "timeline.phase2": "Phase 02",
    "timeline.phase2Title": "Creative Exploration & Co-creation",
    "timeline.phase2Desc": "Learners deepen concepts, test ideas, and form demonstrable rural-design prototypes.",
    "timeline.phase3": "Phase 03",
    "timeline.phase3Title": "Incubation & Real-world Transformation",
    "timeline.phase3Desc": "Roadshows, review, selection, and outcome transformation drive agricultural design into practice.",
    "corpus.eyebrow": "Corpus Library",
    "corpus.title": "Four corpus packs provide rural-design signals for concept generation",
    "corpus.viewDetails": "Open corpus page",
    "corpus1.title": "Corpus 1: Smart Agriculture & Production Tech",
    "corpus1.short": "Smart Agriculture & Production Tech",
    "corpus1.desc": "Production-technology signals: AI breeding, remote sensing, autonomous farms, agri foundation models, and pest recognition.",
    "corpus1.signals": "AG-01 to AG-30",
    "corpus1.use": "Smart production, precision agriculture, agri intelligence",
    "corpus2.title": "Corpus 2: Rural Brand & Cultural-creative",
    "corpus2.short": "Rural Brand & Cultural-creative",
    "corpus2.desc": "Signals on AIGC generative design, agri-product branding, rural IP incubation, and short-video/live-commerce.",
    "corpus2.signals": "CB-01 to CB-20",
    "corpus2.use": "Brand & culture, IP incubation, content marketing",
    "corpus3.title": "Corpus 3: Digital Village & Platforms",
    "corpus3.short": "Digital Village & Platforms",
    "corpus3.desc": "Signals on rural e-commerce, supply-chain traceability, digital inclusive finance, smart governance, and rural data infrastructure.",
    "corpus3.signals": "DR-01 to DR-20",
    "corpus3.use": "Digital village, platform economy, smart governance",
    "corpus4.title": "Corpus 4: Rural Culture & Sustainability",
    "corpus4.short": "Rural Culture & Sustainability",
    "corpus4.desc": "Signals on heritage/folk-art digitization, rural tourism experience, eco-agriculture carbon neutrality, and public-space design.",
    "corpus4.signals": "CH-01 to CH-20",
    "corpus4.use": "Culture revival, eco-sustainability, community design",
    "cases.eyebrow": "Case Library",
    "cases.title": "Four themed case sets provide reference prototypes for design reasoning",
    "case1.title": "Case Library 1: Smart Agriculture & AI Production",
    "case1.short": "Smart Agriculture & AI Production",
    "case1.desc": "Real deployed projects and enterprise practices in AI breeding, autonomous farms, agri foundation models, and intelligent recognition.",
    "case1.signals": "SA-01 to SA-18",
    "case1.use": "Smart production, precision agriculture, tech pathways",
    "case2.title": "Case Library 2: Rural Brand & AIGC Cultural-creative",
    "case2.short": "Rural Brand & AIGC Cultural-creative",
    "case2.desc": "Real cases in agri-product brand design, rural IP, AIGC packaging/posters, and short-video marketing.",
    "case2.signals": "BD-01 to BD-18",
    "case2.use": "Brand design, IP incubation, content marketing",
    "case3.title": "Case Library 3: Digital Village & Platforms",
    "case3.short": "Digital Village & Platforms",
    "case3.desc": "Real deployed projects in rural e-commerce, digital governance, traceability, and smart tourism platforms.",
    "case3.signals": "DV-01 to DV-18",
    "case3.use": "Digital village, platform economy, public service",
    "case4.title": "Case Library 4: Rural Culture & Sustainable Design",
    "case4.short": "Rural Culture & Sustainable Design",
    "case4.desc": "Real practices in heritage revival, rural public space, eco-agriculture, and community design.",
    "case4.signals": "CS-01 to CS-18",
    "case4.use": "Culture revival, sustainability, community building",
    "workshop.eyebrow": "AI Co-creation Workshop",
    "workshop.title": "Future Design Thinking Workflow",
    "workshop.step1": "Browse and select future signals.",
    "workshop.step2": "Select or enter local challenges, with AI-assisted expansion.",
    "workshop.step3": "Generate a Provotyping Card and an Interpretation sentence.",
    "workshop.step4": "Generate tomorrow's headline and scenario imagery.",
    "workshop.step5": "Backcast actions for 2040 and 2030 from a 2050 goal.",
    "skills.eyebrow": "Codex Skill System",
    "skills.title": "An AI skill suite from future design method to complete project presentation",
    "skills.lede":
      "This skill suite breaks the course workflow into one controller skill and multiple independently callable subskills. Students can move step by step from future signals to method outputs, then continue into reports, slides, visuals, interactive prototypes, storyboards, videos, and local project archives.",
    "skills.controllerLabel": "Controller",
    "skills.controllerDesc":
      "The main controller skill links the complete Future Design Thinking process: framing, future signals, STEEP, local challenge, interpretation, provotyping, tomorrow headline, backcasting, final proposal, and production.",
    "skills.projectControllerLabel": "Full Project",
    "skills.projectControllerDesc":
      "A project-level controller subskill that connects the method phase, production routing, asset archiving, and final delivery check into one continuous project workflow.",
    "skills.phaseA": "Method Exploration",
    "skills.phaseADesc": "Create future signals, STEEP, local challenge, signal-challenge pairing, interpretation, and concept card.",
    "skills.phaseB": "Future Narrative & Roadmap",
    "skills.phaseBDesc": "Turn the concept into a tangible future headline and an actionable backcasting route.",
    "skills.phaseC": "Production",
    "skills.phaseCDesc": "Recommend a fitting mix of deliverables and route into document, slide, image, prototype, and video skills.",
    "skills.phaseD": "Archive & Delivery",
    "skills.phaseDDesc": "Store method outputs, generated assets, prompts, source files, and final deliverables in each student's local project folder.",
    "skills.archiveEyebrow": "Local Archive",
    "skills.archiveTitle": "Each student keeps a structured project folder",
    "skills.archiveDesc":
      "The skills organize projects into 00_project-brief, 01_method-process, 03_visual-assets, 04_prototypes, 05_documents, 06_presentations, 07_video-audio, 08_delivery, and 09_ai-process-log so process, assets, and final submission remain traceable.",
    "skills.downloadEyebrow": "Download",
    "skills.downloadTitle": "Download or install this skill suite",
    "skills.downloadDesc": "Download the full suite to preserve the controller-to-subskill relationship, or open an individual skill to inspect its SKILL.md.",
    "skills.downloadZip": "Download ZIP",
    "skills.openGithub": "Open Skills Folder",
    "skills.installLabel": "Codex install command",
    "skills.queryLabel": "Quick validation queries",
    "skills.query1": "List the Future Design related skills currently installed.",
    "skills.query2": "Use future-design-project-controller to check: if my topic is county-level agri-product brand and rural design, what sequence would you guide me through? List stage names only; do not generate a proposal.",
    "skills.query3": "Use future-signal-scout to list only 3 future signal titles for county-level agri-product brand and rural design. Do not expand the analysis.",
    "skills.query4": "Start Future Design Project Controller and dry-run the full workflow: list what each step reads from the previous step, which skill it calls, and what artifact it creates. Do not generate actual proposal content.",
    "skills.query5": "Note: these queries only validate installation, triggering, and workflow routing. A complete proposal still needs to be completed step by step through the workshop.",
    "outputs.eyebrow": "Outputs",
    "outputs.title": "AI co-creation workshop outputs",
    "outputs.proto": "A combination of future signals and local challenges used to define opportunities and tensions.",
    "outputs.interpretation": "A discussable and editable sentence that connects the A, B, and C elements.",
    "outputs.headline": "A perceptible future presented as 2030, 2040, or 2050 news headlines.",
    "outputs.backcasting": "Action pathways backcast through roles such as county head, enterprise leader, and individual actor.",
    "support.eyebrow": "Technical Support",
    "support.title": "Need help? Scan to contact us",
    "support.desc": "For technical issues, token recharge, API configuration, or any other questions, scan the QR code to contact manta.ai via WeChat.",
    "support.scan": "Scan to add on WeChat",
    "toolsSection.eyebrow": "Tools",
    "toolsSection.title": "Tools & Setup",
    "toolsSection.codexDesc": "Install Codex CLI and configure the mantai LLM API service.",
    "toolsSection.skillDesc": "Download and install workshop and multimodal generation Skills.",
    "toolsSection.verifyDesc": "Verify that Skills and API configuration are working correctly.",
  },
};

function applyLanguage(lang) {
  const current = translations[lang] ? lang : "zh";
  currentLanguage = current;

  document.documentElement.lang = current === "zh" ? "zh-CN" : "en";
  document.title =
    current === "zh"
      ? "国家农业科技创新港·生成式人工智能助农设计人才培训"
      : "Generative AI for Rural Revitalization Design Talent Program";

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    const value = translations[current][key];
    if (value) element.textContent = value;
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.langSwitch === current;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("agri-camp-language", current);
}

const observer = new IntersectionObserver(
  (entries) => {
    const visible = entries
      .filter((entry) => entry.isIntersecting)
      .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];

    if (!visible) return;

    sidebarLinks.forEach((link) => {
      link.classList.toggle("active", link.getAttribute("href") === `#${visible.target.id}`);
    });
  },
  {
    rootMargin: "-18% 0px -70% 0px",
    threshold: [0.1, 0.35, 0.6],
  },
);

sections.forEach((section) => observer.observe(section));

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.langSwitch));
});

applyLanguage(localStorage.getItem("agri-camp-language") || "zh");
